### ISSUE TITLE
database file missing 

### ISSUE THREAD

**Issue by mucahidbaris** [MohammadMahdi-Akhondi/dental_project#1]
wtf sql file

**Comment by MohammadMahdi-Akhondi** [comment]
Hi, at the beginning of the project I was working with PHP 8.1.6 and I could not get export from the phpmyadmin database. Today, after searching several times, I realized that this is a bug in this version, and I changed the PHP version to 8.1.0 so that I can get export from the database.

The database file is now available in the project.
